import { writable } from 'svelte/store'

export const lang = writable('hr') // 'hr' ili 'en'

export function toggleLang() {
  lang.update(l => l === 'hr' ? 'en' : 'hr')
}

// UI tekstovi
export const ui = {
  hr: {
    loginTitle: 'Identifikacija putnika',
    username: 'Korisničko ime',
    password: 'Lozinka',
    login: 'Prijava',
    register: 'Registracija',
    back: '← Natrag',
    loginBtn: 'Prijava / Registracija',
    aboutBtn: 'O PaLANtiru',
    exitBtn: 'Izlaz',
    createNet: 'Stvori novu mrežu',
    joinNet: 'Pridruži se postojećoj mreži',
    enterCode: 'Upiši kod mreže:',
    codePlaceholder: 'Kod mreže',
    join: 'Pridruži se',
    netCreated: 'Mreža kreirana! Kod:',
    shareCode: 'Podijeli ovaj kod s prijateljem',
    startTunnel: 'Pokreni tunel',
    creating: 'Kreiranje...',
    connecting: 'Spajanje...',
    starting: 'Pokretanje...',
    user: 'Korisnik',
    virtualIP: 'Virtualna IP',
    netCode: 'Kod mreže',
    peers: 'Peerovi',
    log: 'Dnevnik',
    disconnect: 'Prekini vezu',
    waitingPeers: 'Čekam pridruživanje peerova...',
    waitingActivity: 'Čekam aktivnost...',
    connected: 'Spojen',
    connectingStatus: 'Spajanje...',
    disconnected: 'Odspojen',
    loginSuccess: 'Prijava uspješna!',
    registerSuccess: 'Registracija i prijava uspješna!',
    encyclopediaTitle: 'Enciklopedija mrežnih pojmova',
    searchPlaceholder: 'Pretraži pojmove...',
    inPalantir: 'U PaLANtiru:',
  },
  en: {
    loginTitle: 'Traveler Identification',
    username: 'Username',
    password: 'Password',
    login: 'Login',
    register: 'Register',
    back: '← Back',
    loginBtn: 'Login / Register',
    aboutBtn: 'About PaLANtir',
    exitBtn: 'Exit',
    createNet: 'Create new network',
    joinNet: 'Join existing network',
    enterCode: 'Enter network code:',
    codePlaceholder: 'Network code',
    join: 'Join',
    netCreated: 'Network created! Code:',
    shareCode: 'Share this code with a friend',
    startTunnel: 'Start tunnel',
    creating: 'Creating...',
    connecting: 'Connecting...',
    starting: 'Starting...',
    user: 'User',
    virtualIP: 'Virtual IP',
    netCode: 'Network code',
    peers: 'Peers',
    log: 'Log',
    disconnect: 'Disconnect',
    waitingPeers: 'Waiting for peers to join...',
    waitingActivity: 'Waiting for activity...',
    connected: 'Connected',
    connectingStatus: 'Connecting...',
    disconnected: 'Disconnected',
    loginSuccess: 'Login successful!',
    registerSuccess: 'Registration and login successful!',
    encyclopediaTitle: 'Network Concepts Encyclopedia',
    searchPlaceholder: 'Search concepts...',
    inPalantir: 'In PaLANtir:',
  }
}
