// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DoCreateAndStart():Promise<main.CreateResult>;

export function DoGetPeers():Promise<Array<main.PeerStatus>>;

export function DoJoinAndStart(arg1:string):Promise<main.JoinResult>;

export function DoLeaveNetwork():Promise<void>;

export function DoLogin(arg1:string,arg2:string):Promise<void>;

export function DoRegister(arg1:string,arg2:string):Promise<void>;

export function GetNetworkID():Promise<string>;

export function GetServerURL():Promise<string>;

export function GetUsername():Promise<string>;

export function GetVirtualIP():Promise<string>;

export function IsInNetwork():Promise<boolean>;

export function IsLoggedIn():Promise<boolean>;

export function SetServerURL(arg1:string):Promise<void>;
