// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DoCreateAndStart() {
  return window['go']['main']['App']['DoCreateAndStart']();
}

export function DoGetPeers() {
  return window['go']['main']['App']['DoGetPeers']();
}

export function DoJoinAndStart(arg1) {
  return window['go']['main']['App']['DoJoinAndStart'](arg1);
}

export function DoLeaveNetwork() {
  return window['go']['main']['App']['DoLeaveNetwork']();
}

export function DoLogin(arg1, arg2) {
  return window['go']['main']['App']['DoLogin'](arg1, arg2);
}

export function DoRegister(arg1, arg2) {
  return window['go']['main']['App']['DoRegister'](arg1, arg2);
}

export function GetGbFlag() {
  return window['go']['main']['App']['GetGbFlag']();
}

export function GetHrFlag() {
  return window['go']['main']['App']['GetHrFlag']();
}

export function GetNetworkID() {
  return window['go']['main']['App']['GetNetworkID']();
}

export function GetSarumanGif() {
  return window['go']['main']['App']['GetSarumanGif']();
}

export function GetServerURL() {
  return window['go']['main']['App']['GetServerURL']();
}

export function GetUsername() {
  return window['go']['main']['App']['GetUsername']();
}

export function GetVirtualIP() {
  return window['go']['main']['App']['GetVirtualIP']();
}

export function IsInNetwork() {
  return window['go']['main']['App']['IsInNetwork']();
}

export function IsLoggedIn() {
  return window['go']['main']['App']['IsLoggedIn']();
}

export function SetServerURL(arg1) {
  return window['go']['main']['App']['SetServerURL'](arg1);
}
