// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DoCreateNetwork() {
  return window['go']['main']['App']['DoCreateNetwork']();
}

export function DoGetPeers() {
  return window['go']['main']['App']['DoGetPeers']();
}

export function DoJoinNetwork(arg1) {
  return window['go']['main']['App']['DoJoinNetwork'](arg1);
}

export function DoLogin(arg1, arg2) {
  return window['go']['main']['App']['DoLogin'](arg1, arg2);
}

export function DoRegister(arg1, arg2) {
  return window['go']['main']['App']['DoRegister'](arg1, arg2);
}

export function DoStartTunnel() {
  return window['go']['main']['App']['DoStartTunnel']();
}

export function DoStopTunnel() {
  return window['go']['main']['App']['DoStopTunnel']();
}

export function GetNetworkID() {
  return window['go']['main']['App']['GetNetworkID']();
}

export function GetUsername() {
  return window['go']['main']['App']['GetUsername']();
}

export function GetVirtualIP() {
  return window['go']['main']['App']['GetVirtualIP']();
}
