// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DoCreateNetwork():Promise<main.CreateResult>;

export function DoGetPeers():Promise<Array<main.PeerStatus>>;

export function DoJoinNetwork(arg1:string):Promise<main.JoinResult>;

export function DoLogin(arg1:string,arg2:string):Promise<void>;

export function DoRegister(arg1:string,arg2:string):Promise<void>;

export function DoStartTunnel():Promise<void>;

export function DoStopTunnel():Promise<void>;

export function GetNetworkID():Promise<string>;

export function GetUsername():Promise<string>;

export function GetVirtualIP():Promise<string>;
