import { writable } from 'svelte/store'

export const lang = writable('hr')

export function toggleLang() {
  lang.update(l => l === 'hr' ? 'en' : 'hr')
}

export const ui = {
  hr: {
    loginTitle: 'Identifikacija putnika',
    username: 'Korisničko ime',
    password: 'Lozinka',
    login: 'Prijava',
    register: 'Registracija',
    back: '← Natrag',
    loginBtn: 'Prijava / Registracija',
    aboutBtn: 'O PaLANtiru',
    exitBtn: 'Izlaz',
    settingsBtn: 'Postavi server',
    createNet: 'Stvori novu mrežu',
    joinNet: 'Pridruži se postojećoj mreži',
    viewNet: 'Pregled postojeće mreže',
    leaveNet: 'Napusti mrežu',
    enterCode: 'Upiši kod mreže:',
    codePlaceholder: 'Kod mreže',
    join: 'Pridruži se',
    netCreated: 'Mreža kreirana! Kod:',
    shareCode: 'Podijeli ovaj kod s prijateljem — čekam peere...',
    creating: 'Kreiranje...',
    connecting: 'Spajanje...',
    user: 'Korisnik',
    virtualIP: 'Virtualna IP',
    netCode: 'Kod mreže',
    peers: 'Peerovi',
    log: 'Dnevnik',
    disconnect: 'Napusti mrežu',
    backToMenu: '← Izbornik',
    refreshPeers: '↻',
    waitingPeers: 'Čekam pridruživanje peerova...',
    waitingActivity: 'Čekam aktivnost...',
    connected: 'Spojen',
    connectingStatus: 'Spajanje...',
    disconnected: 'Odspojen',
    loginSuccess: 'Prijava uspješna!',
    registerSuccess: 'Registracija i prijava uspješna!',
    encyclopediaTitle: 'Enciklopedija mrežnih pojmova',
    searchPlaceholder: 'Pretraži pojmove...',
    inPalantir: 'U PaLANtiru:',
    serverUrl: 'Adresa servera',
    serverPort: 'Port',
    save: 'Spremi',
    settingsTitle: 'Postavke servera',
    inNetworkWarning: 'Već ste u mreži. Napustite mrežu prije kreiranja nove.',
  },
  en: {
    loginTitle: 'Traveler Identification',
    username: 'Username',
    password: 'Password',
    login: 'Login',
    register: 'Register',
    back: '← Back',
    loginBtn: 'Login / Register',
    aboutBtn: 'About PaLANtir',
    exitBtn: 'Exit',
    settingsBtn: 'Server Settings',
    createNet: 'Create new network',
    joinNet: 'Join existing network',
    viewNet: 'View current network',
    leaveNet: 'Leave network',
    enterCode: 'Enter network code:',
    codePlaceholder: 'Network code',
    join: 'Join',
    netCreated: 'Network created! Code:',
    shareCode: 'Share this code with a friend — waiting for peers...',
    creating: 'Creating...',
    connecting: 'Connecting...',
    user: 'User',
    virtualIP: 'Virtual IP',
    netCode: 'Network code',
    peers: 'Peers',
    log: 'Log',
    disconnect: 'Leave network',
    backToMenu: '← Menu',
    refreshPeers: '↻',
    waitingPeers: 'Waiting for peers to join...',
    waitingActivity: 'Waiting for activity...',
    connected: 'Connected',
    connectingStatus: 'Connecting...',
    disconnected: 'Disconnected',
    loginSuccess: 'Login successful!',
    registerSuccess: 'Registration and login successful!',
    encyclopediaTitle: 'Network Concepts Encyclopedia',
    searchPlaceholder: 'Search concepts...',
    inPalantir: 'In PaLANtir:',
    serverUrl: 'Server address',
    serverPort: 'Port',
    save: 'Save',
    settingsTitle: 'Server Settings',
    inNetworkWarning: 'Already in a network. Leave it before creating a new one.',
  }
}
